# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biomega2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(481, 401)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(481, 401))
        MainWindow.setMaximumSize(QtCore.QSize(481, 401))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/biomega.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(4, 6, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel{border:none;color: #504B67;}")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{border:none;color: black;}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.AdaptorBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdaptorBox.sizePolicy().hasHeightForWidth())
        self.AdaptorBox.setSizePolicy(sizePolicy)
        self.AdaptorBox.setMinimumSize(QtCore.QSize(0, 25))
        self.AdaptorBox.setStyleSheet("QComboBox{\n"
"    border:1px solid gray;\n"
"    border-radius:4px;\n"
"    padding:2px 4px;\n"
"}")
        self.AdaptorBox.setObjectName("AdaptorBox")
        self.AdaptorBox.addItem("")
        self.AdaptorBox.addItem("")
        self.AdaptorBox.addItem("")
        self.AdaptorBox.addItem("")
        self.verticalLayout.addWidget(self.AdaptorBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{border:none;color:black;}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ElectrodeBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElectrodeBox.sizePolicy().hasHeightForWidth())
        self.ElectrodeBox.setSizePolicy(sizePolicy)
        self.ElectrodeBox.setMinimumSize(QtCore.QSize(0, 25))
        self.ElectrodeBox.setStyleSheet("QComboBox{\n"
"    border:1px solid gray;\n"
"    border-radius:4px;\n"
"    padding:2px 4px;\n"
"}")
        self.ElectrodeBox.setObjectName("ElectrodeBox")
        self.ElectrodeBox.addItem("")
        self.ElectrodeBox.addItem("")
        self.ElectrodeBox.addItem("")
        self.ElectrodeBox.addItem("")
        self.ElectrodeBox.addItem("")
        self.verticalLayout.addWidget(self.ElectrodeBox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("QLabel{border:none;color: #504B67;}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.IMPButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IMPButton.sizePolicy().hasHeightForWidth())
        self.IMPButton.setSizePolicy(sizePolicy)
        self.IMPButton.setMinimumSize(QtCore.QSize(0, 30))
        self.IMPButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.IMPButton.setObjectName("IMPButton")
        self.verticalLayout_2.addWidget(self.IMPButton)
        self.ELEButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ELEButton.sizePolicy().hasHeightForWidth())
        self.ELEButton.setSizePolicy(sizePolicy)
        self.ELEButton.setMinimumSize(QtCore.QSize(0, 30))
        self.ELEButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.ELEButton.setObjectName("ELEButton")
        self.verticalLayout_2.addWidget(self.ELEButton)
        self.MANButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MANButton.sizePolicy().hasHeightForWidth())
        self.MANButton.setSizePolicy(sizePolicy)
        self.MANButton.setMinimumSize(QtCore.QSize(0, 30))
        self.MANButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.MANButton.setObjectName("MANButton")
        self.verticalLayout_2.addWidget(self.MANButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(15, 2, 6, 2)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{border:none;color:#4A2429}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.DeviceButton = QtWidgets.QCheckBox(self.layoutWidget)
        self.DeviceButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeviceButton.sizePolicy().hasHeightForWidth())
        self.DeviceButton.setSizePolicy(sizePolicy)
        self.DeviceButton.setText("")
        self.DeviceButton.setObjectName("DeviceButton")
        self.horizontalLayout_4.addWidget(self.DeviceButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.ScanButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ScanButton.setMinimumSize(QtCore.QSize(90, 0))
        self.ScanButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: left center;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.ScanButton.setObjectName("ScanButton")
        self.horizontalLayout_4.addWidget(self.ScanButton)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    border:1px solid gray;\n"
"    border-radius:4px;\n"
"    padding:2px 4px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_4.addWidget(self.comboBox_3)
        self.OpenButton = QtWidgets.QPushButton(self.layoutWidget)
        self.OpenButton.setMinimumSize(QtCore.QSize(120, 0))
        self.OpenButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: left center;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.OpenButton.setObjectName("OpenButton")
        self.horizontalLayout_4.addWidget(self.OpenButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(66)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.stackedWidget.setSizeIncrement(QtCore.QSize(100, 0))
        self.stackedWidget.setBaseSize(QtCore.QSize(500, 0))
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    border:none;\n"
"    \n"
"  }  \n"
" border-bottom-right-radius:10px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.during_time = QtWidgets.QSpinBox(self.page)
        self.during_time.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.during_time.setFont(font)
        self.during_time.setMaximum(10000)
        self.during_time.setSingleStep(100)
        self.during_time.setObjectName("during_time")
        self.horizontalLayout_2.addWidget(self.during_time)
        self.label_8 = QtWidgets.QLabel(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.pause_time = QtWidgets.QSpinBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_time.sizePolicy().hasHeightForWidth())
        self.pause_time.setSizePolicy(sizePolicy)
        self.pause_time.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.pause_time.setFont(font)
        self.pause_time.setObjectName("pause_time")
        self.horizontalLayout_3.addWidget(self.pause_time)
        self.label_10 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalSlider = QtWidgets.QSlider(self.page)
        self.horizontalSlider.setStyleSheet("QSlider{border:none;}\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    border-radius: 10px;\n"
"    background: lightgray;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    border: none;\n"
"    margin: -5px 0px; /* 上下边距和左右边距*/\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    background:black;\n"
"    border-image: url(:/images/playPbHandle16_White.png);\n"
"}\n"
"/*划过部分*/\n"
"QSlider::sub-page:horizontal {\n"
"    background: black;\n"
"    height: 4px;\n"
"    border-radius: 3px;\n"
"}\n"
"/*未划过部分*/\n"
"QSlider::add-page:horizontal {\n"
"    background: lightgray;\n"
"    height: 4px;\n"
"    border-radius: 3px;\n"
"}\n"
" #e83c3c;")
        self.horizontalSlider.setMaximum(4095)
        self.horizontalSlider.setSliderPosition(2048)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_6.addWidget(self.horizontalSlider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setGeometry(QtCore.QRect(0, -20, 321, 311))
        font = QtGui.QFont()
        font.setFamily("Candara")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_23.setFont(font)
        self.label_23.setScaledContents(False)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 311, 261))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 2, -1, 4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.Imp_radioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.Imp_radioButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.Imp_radioButton.setFont(font)
        self.Imp_radioButton.setChecked(True)
        self.Imp_radioButton.setObjectName("Imp_radioButton")
        self.verticalLayout_7.addWidget(self.Imp_radioButton)
        self.Ele_radioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.Ele_radioButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.Ele_radioButton.setFont(font)
        self.Ele_radioButton.setObjectName("Ele_radioButton")
        self.verticalLayout_7.addWidget(self.Ele_radioButton)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 2, -1, 4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setCurrentText("1")
        self.comboBox_4.setMaxCount(65)
        self.comboBox_4.setFrame(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_8.addWidget(self.comboBox_4, 0, QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, 2, -1, 4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_7.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.horizontalLayout_7.setStretch(1, 2)
        self.horizontalLayout_7.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setItalic(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_10.addWidget(self.label_24)
        self.man_during_time = QtWidgets.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setItalic(True)
        self.man_during_time.setFont(font)
        self.man_during_time.setMaximum(1000)
        self.man_during_time.setSingleStep(100)
        self.man_during_time.setObjectName("man_during_time")
        self.horizontalLayout_10.addWidget(self.man_during_time)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_10.addWidget(self.label_25)
        self.horizontalLayout_10.setStretch(0, 2)
        self.horizontalLayout_10.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalSlider_2.setStyleSheet("QSlider{border:none;}\n"
"QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 6px;\n"
"    border-radius: 10px;\n"
"    background: lightgray;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    border: none;\n"
"    margin: -5px 0px; /* 上下边距和左右边距*/\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    background:black;\n"
"    border-image: url(:/images/playPbHandle16_White.png);\n"
"}\n"
"/*划过部分*/\n"
"QSlider::sub-page:horizontal {\n"
"    background: black;\n"
"    height: 4px;\n"
"    border-radius: 3px;\n"
"}\n"
"/*未划过部分*/\n"
"QSlider::add-page:horizontal {\n"
"    background: lightgray;\n"
"    height: 4px;\n"
"    border-radius: 3px;\n"
"}\n"
" #e83c3c;")
        self.horizontalSlider_2.setMaximum(4095)
        self.horizontalSlider_2.setSliderPosition(2048)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_10.addWidget(self.horizontalSlider_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_8.addWidget(self.label_19)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber.setStyleSheet("QLCDNumber{border:none;}")
        self.lcdNumber.setDigitCount(7)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_8.addWidget(self.lcdNumber)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 5)
        self.horizontalLayout_8.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_10.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{border:none;color: #504B67;}")
        self.label_14.setText("")
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setPixmap(QtGui.QPixmap(":/image/logo.jpg"))
        self.label_14.setWordWrap(True)
        self.label_14.setIndent(0)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 6, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StartButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StartButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.StartButton.setAutoRepeat(False)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_3.addWidget(self.StartButton)
        self.CancelButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
        self.CancelButton.setSizePolicy(sizePolicy)
        self.CancelButton.setMinimumSize(QtCore.QSize(0, 0))
        self.CancelButton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.CancelButton.setObjectName("CancelButton")
        self.verticalLayout_3.addWidget(self.CancelButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setRowStretch(0, 8)
        self.gridLayout_2.setRowStretch(1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 481, 381))
        self.listWidget.setStyleSheet("background-image: url(:/image/gg4.jfif);")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.comboBox_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Biomega"))
        self.label.setText(_translate("MainWindow", "Electrode\n"
"Configuration"))
        self.label_3.setText(_translate("MainWindow", "                 Adaptor"))
        self.AdaptorBox.setItemText(0, _translate("MainWindow", "No Adaptor"))
        self.AdaptorBox.setItemText(1, _translate("MainWindow", "MMA-32"))
        self.AdaptorBox.setItemText(2, _translate("MainWindow", "MMA-64"))
        self.AdaptorBox.setItemText(3, _translate("MainWindow", "Prof.Dr.Lu"))
        self.label_2.setText(_translate("MainWindow", "                 Electrode"))
        self.ElectrodeBox.setItemText(0, _translate("MainWindow", "No Electrode"))
        self.ElectrodeBox.setItemText(1, _translate("MainWindow", "BOSS MA"))
        self.ElectrodeBox.setItemText(2, _translate("MainWindow", "Teacher MA"))
        self.ElectrodeBox.setItemText(3, _translate("MainWindow", "Lil MA"))
        self.ElectrodeBox.setItemText(4, _translate("MainWindow", "World MA"))
        self.label_4.setText(_translate("MainWindow", "Mode Selection"))
        self.IMPButton.setText(_translate("MainWindow", "Test Impedances"))
        self.ELEButton.setText(_translate("MainWindow", "DC Electroplate"))
        self.MANButton.setText(_translate("MainWindow", "Manual Control"))
        self.label_6.setText(_translate("MainWindow", "Device"))
        self.ScanButton.setText(_translate("MainWindow", "scan port"))
        self.OpenButton.setText(_translate("MainWindow", "open device"))
        self.label_7.setText(_translate("MainWindow", "     During Time:"))
        self.label_8.setText(_translate("MainWindow", "ms"))
        self.label_9.setText(_translate("MainWindow", "     Pause  Time:"))
        self.label_10.setText(_translate("MainWindow", "S"))
        self.label_11.setText(_translate("MainWindow", "     Plating Current:"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "uA"))
        self.label_15.setText(_translate("MainWindow", "     Present Plating Channel:"))
        self.label_16.setText(_translate("MainWindow", "0"))
        self.label_23.setText(_translate("MainWindow", "I heard, that you settled down.\n"
"That you, found a girl and you married now.\n"
"I heard that your dreams came true.\n"
"Guess she gave you things, I didn\'t give to you.\n"
"Old friend, why are you so shy?\n"
"It ain\'t like you to hold back or hide from the lie.\n"
"I hate to turn up out of the blue uninvited.\n"
"But I couldn\'t stay away, I couldn\'t fight it.\n"
"I\'d hoped you\'d see my face and that you\'d be reminded,\n"
"That for me, it isn\'t over.\n"
"Nevermind, I\'ll find someone like you.\n"
"I wish nothing but the best, for you too.\n"
"Don\'t forget me, I beg, I remember you said:-\n"
"\"Sometimes it lasts in love but sometimes it hurts instead\""))
        self.label_5.setText(_translate("MainWindow", "Mode Selection"))
        self.Imp_radioButton.setText(_translate("MainWindow", "Impedance"))
        self.Ele_radioButton.setText(_translate("MainWindow", "Ele Plating"))
        self.label_17.setText(_translate("MainWindow", "Target Channel"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "32"))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "33"))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "34"))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "35"))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "36"))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "37"))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "38"))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "39"))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "40"))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "41"))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "42"))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "43"))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "44"))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "45"))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "46"))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "47"))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "48"))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "49"))
        self.comboBox_4.setItemText(49, _translate("MainWindow", "50"))
        self.comboBox_4.setItemText(50, _translate("MainWindow", "51"))
        self.comboBox_4.setItemText(51, _translate("MainWindow", "52"))
        self.comboBox_4.setItemText(52, _translate("MainWindow", "53"))
        self.comboBox_4.setItemText(53, _translate("MainWindow", "54"))
        self.comboBox_4.setItemText(54, _translate("MainWindow", "55"))
        self.comboBox_4.setItemText(55, _translate("MainWindow", "56"))
        self.comboBox_4.setItemText(56, _translate("MainWindow", "57"))
        self.comboBox_4.setItemText(57, _translate("MainWindow", "58"))
        self.comboBox_4.setItemText(58, _translate("MainWindow", "59"))
        self.comboBox_4.setItemText(59, _translate("MainWindow", "60"))
        self.comboBox_4.setItemText(60, _translate("MainWindow", "61"))
        self.comboBox_4.setItemText(61, _translate("MainWindow", "62"))
        self.comboBox_4.setItemText(62, _translate("MainWindow", "63"))
        self.comboBox_4.setItemText(63, _translate("MainWindow", "64"))
        self.label_18.setText(_translate("MainWindow", "  Plating Current"))
        self.label_21.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "uA"))
        self.label_24.setText(_translate("MainWindow", " time"))
        self.label_25.setText(_translate("MainWindow", "ms"))
        self.label_19.setText(_translate("MainWindow", "Present \n"
"Impdance:"))
        self.label_20.setText(_translate("MainWindow", "MOhm"))
        self.StartButton.setText(_translate("MainWindow", "START"))
        self.CancelButton.setText(_translate("MainWindow", "CANCEL"))
import icon_rc
import logo_rc
import picture2_rc
import picture3_rc
import picture4_rc
import picture_rc
