# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(441, 716)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/biomega.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        self.tableView = QtWidgets.QTableView(dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 421, 641))
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 650, 421, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setText("")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setInputMask("#.#")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setMaximum(2000)
        self.spinBox.setSingleStep(100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.platebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.platebutton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.platebutton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: aligncenter;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.platebutton.setAutoRepeat(False)
        self.platebutton.setObjectName("platebutton")
        self.verticalLayout_2.addWidget(self.platebutton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.savebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.savebutton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.savebutton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.savebutton.setAcceptDrops(False)
        self.savebutton.setStyleSheet("QPushButton {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: #504B67;\n"
"    font-style: italic;\n"
"    font-weight: bold;\n"
"\n"
"    text-align: left center;\n"
"    padding-left:3px;\n"
"    padding-top: 0px;\n"
"\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: #666666;\n"
"    border-radius: 10px;\n"
"\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-radius: 10px;\n"
"\n"
"\n"
"    background-color: #D1C9B7;\n"
"    background-repeat: no-repeat;\n"
"    background-position: aligncenter;\n"
"}\n"
"QPushButton:hover{\n"
"    color:#FFF5EE;;\n"
"    border-color:#666666; \n"
"    background-color: #D2B48C;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #504B67;\n"
"    border-color:#F4A460;\n"
"    background-color:#F0FFFF;\n"
"}")
        self.savebutton.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.savebutton.setText("save \n"
"data ")
        self.savebutton.setCheckable(False)
        self.savebutton.setAutoDefault(True)
        self.savebutton.setDefault(False)
        self.savebutton.setFlat(False)
        self.savebutton.setObjectName("savebutton")
        self.horizontalLayout_4.addWidget(self.savebutton)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "author----roomaker"))
        self.label_2.setText(_translate("dialog", "mark eligible channels"))
        self.label.setText(_translate("dialog", "greater than"))
        self.lineEdit.setText(_translate("dialog", "0.8"))
        self.label_3.setText(_translate("dialog", "Mohm"))
        self.lineEdit_2.setText(_translate("dialog", "0"))
        self.label_4.setText(_translate("dialog", "uA"))
        self.label_5.setText(_translate("dialog", "ms"))
        self.platebutton.setText(_translate("dialog", "plate channels"))
import icon_rc
